name: Prettier Auto Format

on: push

jobs:
    format:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            # 获取本次 push 改动的文件
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v44

            # 只格式化修改过的文件，自动用你的 .prettierrc
            - name: Format changed files
              if: steps.changed-files.outputs.all_changed_files != ''
              run: npx prettier --write ${{ steps.changed-files.outputs.all_changed_files }}

            # 自动提交格式化后的代码
            - name: Commit & Push changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'style: auto format code'
                  file_pattern: '.'
